name: Build

on:
  push:
    branches:
      - master


jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clone should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=swiggy
            -Dsonar.projectName=swiggy
            -Dsonar.sources=.
      - name: NPM Install
        run: npm install
        
      - name: Docker build and push
        run: |
          # Run commands to build and push Docker images
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 204615365209.dkr.ecr.us-east-1.amazonaws.com
          docker build -t tony-repo .
          docker tag tony-repo:latest 204615365209.dkr.ecr.us-east-1.amazonaws.com/tony-repo:latest
          docker push 204615365209.dkr.ecr.us-east-1.amazonaws.com/tony-repo:latest
        env:
          DOCKER_CLI_ACI: 1
  deploy:
   needs: build
   runs-on: [self-hosted]
   steps:
      - name: docker pull image
        run: docker pull 204615365209.dkr.ecr.us-east-1.amazonaws.com/tony-repo:latest
      - name: Image scan
        run: trivy image 204615365209.dkr.ecr.us-east-1.amazonaws.com/tony-repo:latest > trivyimagedeploy.txt
      - name: Deploy to container
        run: docker run -d --name swiggy-clone -p 3000:3000 204615365209.dkr.ecr.us-east-1.amazonaws.com/tony-repo:latest
      - name: Update kubeconfig
        run: aws eks --region us-east-1 update-kubeconfig --name EKS_CLOUD
      - name: Deploy to kubernetes
        run: kubectl apply -f deployment-service.yml
